### ISSUE TITLE
The user needs to be different

### ISSUE THREAD

**Issue by ktemple-wt** [tester-wt/fun-app#5]
That was the problem all along.

**Comment by ktemple-wt** [comment]
Here's a GitHub comment.

**Comment by ktemple-wt** [comment]
GitHub

**Comment by ktemple-wt** [comment]
EB22CE299264FD65FD5E47C92BB57447350C81278F6695CE022D7B5C9557C54B

**Comment by ktemple-wt** [comment]
It works ok

**Comment by tester-wt** [comment]
@ JIRAUSER - karim.temple::
 from Jira 2

**Comment by tester-wt** [comment]
@ JIRAUSER - karim.temple::
 from Jira AWS

**Comment by ktemple-wt** [comment]
from GitHub AWS
