### ISSUE TITLE
Issue from AWS

### ISSUE THREAD

**Issue by ktemple-wt** [tester-wt/fun-app#6]
This issue was routed through agi-test-466993277.us-east-2.elb.amazonaws.com

**Comment by tester-wt** [comment]
@ JIRAUSER - karim.temple::
 Making comments in *Jira* is fun\!

Here’s a code snippet, too:

{code}let value = "value"
console.log(`The value is ${value}`){code}

**Comment by ktemple-wt** [comment]
Making comments in GitHub is a blast.

Here's some more code:
```sh
#!/bin/bash
value="value"
echo "The value is $value"
```
