### ISSUE TITLE
Jira issue from AWS

### ISSUE THREAD

**Issue by tester-wt** [tester-wt/fun-app#7]

**Comment by ktemple-wt** [comment]
A comment to end all comments.

- Power
- Poise
- Prestige

**Comment by ktemple-wt** [comment]
Powers of the GitHub user:

- Cunning
- Charming
- Coding

**Comment by tester-wt** [comment]
@ JIRAUSER - karim.temple::
 Steps to testing comments:

# Send comment
# Check target
# Rejoice
